version: "2"
services:
  blog:
    build: .
    ports: 
      - "5007:5007"
    volumes:
      - ./database:/myapp/database
  main-flow:
    image: postman/newman_alpine33
    command:
      run Blog-API.postman_collection.json
      --environment Blog-API.postman_collection.json
      --folder main-flow
      -r cli
      --delay-request 500
      --iteration-count 1
      --color on
      --global-var "APIURL=http://127.0.0.1:5007/api"
      --global-var "USERNAME=oznerol"
      --global-var "EMAIL=oz@gmail.com"
      --global-var "PASSWORD=abc123"
    volumes:
      - ./tests/postman:/etc/newman